### ISSUE TITLE
Does the Maple Bootloader code work ?

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [gbulmer/openstm32sw#2]
I tried compiling the bootloader code, and flashed to my STM Disco F407 but although the LED flashes, nothing appears on USB.

I have both usb cabled plugged in, so I was wondering if that code had ever been tested and verified as working.

I also can't find where the original source came from, as if it was ala42, that account no longer contains any repos :-(

**Comment by gbulmer** [comment]
IIRC, yes, the original source code was from ala42. Sorry Roger.

**Comment by rogerclarkmelbourne** [comment]
OK...

I checked   https://github.com/ala42  but I could not see any code, so perhaps they deleted their repos

Do you recall ever building and getting the bootloader working ?

The build settings are for the Discovery F4, and I have that board, so I compiled and uploaded to the Disco, but unfortunatly the USB side of the bootloader did not work.

Its possible that it used an older version of gcc (even older than 4.8 which the Arduino IDE uses), as I tried 4.8 and it didnt help.

Looking at the files, the USB source code, seems to be virtually identical to the F1 version of the Maple bootloader which we now call the stm32duino bootloader

If I get time I was considering just trying duplicating the F1 bootloader and copying in the hardware register defines etc (which I know are different on the F4), and see how much of it works.

I imagine that the GPIO stuff e.g. flashing the LED would probably be fairly easy to get working, but the USB stuff will be harder

**Comment by gbulmer** [comment]
Roger

No I never built that bootloader.
I had some old F4 discovery, and so *may* have tried, but I have no memory
of doing it. Hence I am reasonably sure I never got it going.
I just played with the standard ST F4 'peripheral library' examples, and
either used the on-board programmer, or a proper ST programmer to upload
code.

There were a couple of people on the old LeafLabs forum who did do some
experiments. I remember ala42, and maybe a couple of others, working on it.

Sorry

GB

**Comment by rogerclarkmelbourne** [comment]
No worries...

Thanks for replying.

If I eventually get it working or use bits of it I'll let you know
